// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilbtzkzqqewdqcjhsloj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYnR6a3pxcWV3ZHFjamhzbG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk5NDAsImV4cCI6MjA2NTU5NTk0MH0.3P80fZlOGRurIIPvMOc69lAmWh16t433aqARIhOG0no";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);